modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="better_creative_tabs"
version="${file.jarVersion}" #mandatory
displayName="Better Creative Tabs" #mandatory
logoFile="better_creative_tabs.png" #optional
credits="Lcy0x1" #optional
authors="Lcy0x1" #optional
description='''
'''
[[dependencies.better_creative_tabs]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_creative_tabs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"